### PR TITLE
Adds Concentration Unit draft ASC

### PR DESCRIPTION
**Pull request by ahadik**
So I have no idea what I'm doing so here is a proposal on how to add concentration to Autoprotocol. I think the biggest sticking point will be the `item` concept. But I do think we need a way to capture some arbitrary number of things per unit of volume. Any other ways to accomplish this would be greatly appreciated.

As for the mass and molarity concentrations, I think this is a pretty reasonable approach.

### CODE REVIEW

**Comment by pleaderlee** [comment]
Are there instructions where concentration units should be used? Currently Autoprotocol is explicit in terms of instructions and we try to minimize calculations/logic that would need to happen in an instruction. We should have a larger discussion on whether we want to keep that style and perhaps the first things we should identify would be what instructions we want to contain concentration units.

**Comment by ahadik** [comment]
@pleaderlee presumably something like https://github.com/autoprotocol/ascs/blob/master/Specification/Instructions/measure_concentration.md or https://github.com/autoprotocol/ascs/blob/master/Specification/Instructions/illumina_library_prep.md would benefit from this?

**Comment by yangchoo** [comment]
@ahadik Any interest in resurrecting this PR and pushing it through to be part of the spec?

I think it generally looks good if we can separate out the `ItemConcentration` portion. That pattern requires more thought and I would prefer if we could separate out the specific additions (MassConcentration, MolarConcentration) from the generalization (ItemConcentration) pattern.

**Review by yangchoo — APPROVED** [review]
This looks perfectly acceptable as a draft.

In terms of moving it forward as a Proposal, there are some sections which I would prefer we change (specifically with regards to the `ItemConcentration` portion).

**Pull request merged**
